# Generated by Django 4.2.2 on 2023-06-24 06:45

import django.core.validators
from django.db import migrations, models
import regular_exam.my_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, message='It should consist of a minimum of 2 characters!'), regular_exam.my_web.models.validate_name_starts_with_letter])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1, message='It should consist of a minimum of 1 characters!'), regular_exam.my_web.models.validate_name_starts_with_letter])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='It should consist of a minimum of 8 characters!')])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
